language: php

php:
  - 5.6
  - 5.5
  - hhvm
before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require comocode/laravel-ab dev-master
  - composer update
  - touch storage/database.sqlite
  - cp .vendor/comocode/laravel-ab/tests/source/laravel/app.php ./config/app.php
  - cd ./vendor/comocode/laravel-ab

script: "phpunit"

